### ISSUE TITLE
Blocks example

### ISSUE THREAD

**Issue by argideritzalpea** [freddyaboulton/gradio-pdf#1]
Is this able to be easily used with Gradio 'Blocks' as opposed to 'Interface'? Are there any examples?

**Comment by novoforce** [comment]
exactly... im also looking for this

**Comment by freddyaboulton** [comment]
Sorry for the delay! Yes it's possible to use this component in gr.Blocks like any other gradio component. See this demo

https://huggingface.co/spaces/freddyaboulton/gradio_pdf_blocks
