### ISSUE TITLE
PDF Component change Event Fires Twice

### ISSUE THREAD

**Issue by Jocelyne-Smith** [freddyaboulton/gradio-pdf#17]
The change event listener for the PDF component in Gradio appears to be firing twice when a file is uploaded.
I tried the same code with the File component and it only fires once. Please see attached video.

https://github.com/user-attachments/assets/885780cc-5cc1-4e62-b47f-c9e34fdcbb92

Heres my code:

```python

import gradio as gr
from gradio_pdf import PDF

state = gr.State(False)

with gr.Blocks() as app:
    btn = gr.Button("Button", interactive=False)

    def file_change():
        print(state.value)
        state.value = not state.value
        print(state.value)
        return gr.update(interactive=state.value)

    file = PDF(label="Specifications (.pdf)", interactive=True)
    
    file.change(fn=file_change, outputs=btn)

if __name__ == "__main__":
    app.launch()

```

**Comment by freddyaboulton** [comment]
Fixed in version 0.0.20! Thank you and sorry for the delay
