### ISSUE TITLE
When using the example module to load PDFs in version 0.16, the PDF files will be downloaded many times repeatedly

### ISSUE THREAD

**Issue by myhloli** [freddyaboulton/gradio-pdf#25]
https://github.com/user-attachments/assets/fd34c5e5-871a-4514-9d54-d6bce9207c62

Using version 0.15 works fine, but it is not compatible with gradio 5.1.0. I hope this issue can be fixed. Thank you.

**Comment by freddyaboulton** [comment]
Interesting. Can you share the code please?

**Comment by myhloli** [comment]
https://huggingface.co/spaces/opendatalab/MinerU/blob/main/app.py

**Comment by freddyaboulton** [comment]
Fixed in 0.0.17
