### ISSUE TITLE
PDF component change event not working

### ISSUE THREAD

**Issue by abpani** [freddyaboulton/gradio-pdf#27]
I am trying to upload a pdf file.
then highlighting some part of it. and then trying to show the updated file in the same component.

with gr.Column(scale=1):
file = PDF(label="Upload a document", interactive=True)

submit_btn.click(add_text, [chatbot, txt], [chatbot, txt]).then(
bot, [chatbot], [chatbot]).then(
clear_cuda_cache, None
).then(return_output_path, [], file)

It is not working. Please help.

**Comment by freddyaboulton** [comment]
Hi @abpani I can't reproduce the change event not working. But the component doesn't not know about file highlighting. The change event triggers when the underlying file changes.
