### ISSUE TITLE
upgrading to current cc development?

### ISSUE THREAD

**Issue by cognitivetech** [freddyaboulton/gradio-pdf#3]
I've been fighting to try and set up a development environment for this component, when I realized this was released using probably 3.41.0... this was shortly before the codebase became modularized and more extensible, starting around February.

maybe we can get some AI assistance or, IDK even.. but I want to add more features, and it would be nice to use latest development.

maybe it would be easier to just rebuild this from scratch with the new "cc" module

**Comment by freddyaboulton** [comment]
Hi @cognitivetech ! This is one of the oldest custom components. I'll see if I can update the repo to use latest gradio this week.

**Comment by cognitivetech** [comment]
ok, so I'm still having trouble with this, because regardless of whether I type `gradio cc install` first, once using `gradio cc dev` I'm asked to install a variety of other packages, including `gradio_pdf` (which was disorienting, but ok), but also `tensorflow`, `tensorrt`, right now I'm building tensorflow from source cause whatever I can't get it to work with my gpu.. and while I had a good environment for cuda 12, one of the packages required cuda 11, so I had to reconfigure everything so I can use both..

now after all of this, and finally I'm getting tensorflow to compile, which its been doing for well over an hour now, I'm wondering to myself... Why is it, that I could simply create a development environment to build your huggingface space, but now I'm trying to work on the custom component, do I really need all of this GPU?

Thanks :)

**Comment by freddyaboulton** [comment]
Hi @cognitivetec! No reason to install tensorflow if you don't want it. Not sure what's causing that install honestly. I thought `transformers` did not install pytorch or tensorflow by default.

Please modify the `requirements.txt` and `demo/app.py` to be whatever you'd like. In my case, I used a transformers pipeline to show realistic usage of the component but it can be as simple as you'd like.

**Comment by cognitivetech** [comment]
that makes sense.. I'm just planning to work via api \ ollama... I didnt' drill down was just obeying the terminal output :D 

But I also don't know how everything works, so just having confirmation I can take that out is great, thanks!

**Comment by freddyaboulton** [comment]
Great @cognitivetech - happy to help!
