### ISSUE TITLE
set Interactive to false not worked.

### ISSUE THREAD

**Issue by hellofinch** [freddyaboulton/gradio-pdf#31]
I install the gradio-pdf and imported it as a demo.
but I just want to use the gradio-pdf as an output. I set `interactive=False`.
But nothing changed. I still can click and upload the file.
```
preview = PDF(label="PDF Preview", interactive=False, visible=True)
```
Here is my code. And I try the `interactive` with `Image` and it works.
Is there a bug?
：）

**Comment by freddyaboulton** [comment]
Fixed in version 0.0.20!
