### ISSUE TITLE
[BUG] Chinese character missed

### ISSUE THREAD

**Issue by hellofinch** [freddyaboulton/gradio-pdf#33]
Hello, when I load a PDF with Chinese characters, the Chinese characters miss only English characters.
Here are some snapshots.
![image](https://github.com/user-attachments/assets/4dc00736-98b3-46ba-ac09-9f012fc72217)
![image](https://github.com/user-attachments/assets/c54b54ae-0a4a-454c-970b-4d132fe7d43c)
![image](https://github.com/user-attachments/assets/c3c10657-84b7-4969-969e-05a924774699)

**Comment by freddyaboulton** [comment]
🤔 thanks for filing @hellofinch .Not sure what is happening.

**Comment by hellofinch** [comment]
I guess something happened with `pdf.js`. 🤔
That's interesting.

**Comment by freddyaboulton** [comment]
Can you share the pdf? It happens with all pdfs that you try?

**Comment by hellofinch** [comment]
[3433701.3433723-zh.pdf](https://github.com/user-attachments/files/18104398/3433701.3433723-zh.pdf)
Here you are.
: )

**Comment by freddyaboulton** [comment]
Fixed in #34, available in version 0.0.21!

<img width="626" alt="Screenshot 2024-12-12 at 4 58 24 PM" src="https://github.com/user-attachments/assets/853a0479-7d80-4a68-8ea6-f8ce40746b0d" />
